# -*- coding: utf-8 -*-
"""diabetes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T3fc_0Gdi7a8xUEMP3zUZe76Smxs0MbC
"""

import pandas as pd

diabetes=pd.read_csv('https://github.com/YBI-Foundation/Dataset/raw/main/Diabetes.csv')

diabetes.head()

diabetes.columns

diabetes.info()

diabetes.tail()

diabetes.describe()

diabetes.describe(include='all')

diabetes.shape

diabetes['glucose']

diabetes['glucose'].shape

diabetes[['glucose']]

diabetes[['glucose']].shape

diabetes['glucose'].unique()

diabetes['glucose'].nunique()

diabetes['glucose'].value_counts()

diabetes.isna().sum()

diabetes.isnull().sum()
#is same as above

y=diabetes['diabetes']

X=diabetes[['pregnancies','glucose','diastolic','triceps','insulin','bmi','dpf','age']]

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.7,stratify=y,random_state=2529)

X_train.shape,X_test.shape,y_train.shape,y_test.shape

X_train